# Generated by Django 5.2.7 on 2025-11-10 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyStreakLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streak_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'study_streak_logs',
                'ordering': ['date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
